services:
  postgres:
    image: postgres:17-alpine
    container_name: pdfstorage-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pdfstorage-web-api:
    image: pdfstorage-web-api:latest
    container_name: pdfstorage-web-api
    build:
      context: .
      dockerfile: PdfStorageWebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PostgresConnection=Host=postgres;Port=5432;Database=pdfStorage;Username=postgres;Password=123
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: